variables:
  CI_DEBUG_SERVICES: "true"

before_script:
  - apk update
  - apk --no-cache add py3-pip python3 curl gettext
  - python3 -m venv $HOME/.venv
  - export PATH=$HOME/.venv/bin:$PATH
  - pip3 install pyyaml
  - curl -O https://raw.githubusercontent.com/FredHutch/swarm-build-helper/main/build_helper.py
  # below is from https://stackoverflow.com/a/65810302/470769
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - set -x

stages:
  - build
  # - test
  - deploy

build:
  stage: build
  script:
    - set -e
    - echo $DOTENV_BASE64_ENCODED | base64 -d > .env
    - echo $DOTENV2_BASE64_ENCODED | base64 -d > .env2
    - source .env
    - set -a
    - source .env2
    - set +a
    - docker build -t sc-registry.fredhutch.org/db4sci:$CI_COMMIT_SHORT_SHA .

# TODO figure this out
#   stage: test
#   services:
#     - name: sc-registry.fredhutch.org/db4sci:$CI_COMMIT_SHORT_SHA
#       alias: db4sci
#   script:
#     - sleep 120
#     - response=$(curl -si http://db4sci:5008 )
#     - echo "result of curl is $?"
#     - echo $response
#     - echo $response|head -1 |grep -q "200 OK"
#     - if [[ -n "$CI_COMMIT_BRANCH" ]] && [[ "$CI_COMMIT_BRANCH" != "main" ]]; then docker rmi sc-registry.fredhutch.org/db4sci:$CI_COMMIT_SHORT_SHA ; fi

deploy:
  stage: deploy
  only:
    refs:
        - deployment-prep
  script:
    - docker tag sc-registry.fredhutch.org/db4sci:$CI_COMMIT_SHORT_SHA sc-registry.fredhutch.org/db4sci:latest
    - docker push sc-registry.fredhutch.org/db4sci:latest
    - docker rmi sc-registry.fredhutch.org/db4sci:$CI_COMMIT_SHORT_SHA
    - sleep 15
    - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    - chmod 0400 ./sc_swarm_cicd_ssh_key
    - cat docker-compose.yml | envsubst | python3 build_helper.py --fluentd-logging - | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --with-registry-auth -c - db4sci
