version: '2'

services:
    mydb:
        image: mydb:1.7.0
        build:
            context: .
        container_name: mydb

        #  Expose ports without publishing them to the host machine
        #  they’ll only be accessible to linked services. Only the internal port can be specified.
        expose: 
          - "5000"

        environment:
            - "TZ=America/Los_Angeles"
            - DB4SCI_MODE=${DB4SCI_MODE}
            - HOSTNAME=${HOSTNAME}
            - HOST_IP=${HOST_IP}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_BUCKET=${AWS_BUCKET}

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/log/uwsgi:/var/log/uwsgi

            - /mydb/db_data:/mydb/db_data
            - /mydb/db_backups:/mydb/db_backups


        privileged: false
        restart: always

    web:
        image: mydb-web:1.0
        build:
            context: ${DB4SCI_MODE}/nginx

        container_name: mydb-web 
        ports:
            - "80:80"
            - "443:443"

        links:
            - mydb:mydb

        depends_on:
            - mydb

        environment:
            - "TZ=America/Los_Angeles"

        volumes:
            - /mydb/logs/nginx:/var/log/nginx

        privileged: true

        restart: always
